version: '3.8'

services:
  streamlit-app:
    build: .
    container_name: vib-credit-card-classifier
    ports:
      - "8504:8501"
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
